fail_fast: true
default_stages: [commit]
repos:
  - hooks:
      - id: end-of-file-fixer
        stages: [commit, manual]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - args:
          - --fix
          - --exit-non-zero-on-fix
        id: ruff
        stages: [commit, manual]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
  - hooks:
      - id: isort
        stages: [commit, manual]
        name: isort (python)
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
  - hooks:
      - id: black
        stages: [commit, manual]
    repo: https://github.com/psf/black
    rev: 22.10.0
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: cd backend && mypy .
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #       stages: [commit]
  #     - id: commitizen
  #       name: commitizen
  #       entry: cz check --rev-range main...HEAD
  #       language: system
  #       pass_filenames: false
  #       stages: [commit, push]
  #     - id: pytest
  #       stages: [commit]
  #       name: pytest
  #       entry: pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
