default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: pytest
        stages: [commit]
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: cd backend && mypy .
        language: system
        pass_filenames: false
        always_run: true
  - hooks:
      - id: end-of-file-fixer
        stages: [commit, manual]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - args:
          - --fix
          - --exit-non-zero-on-fix
        id: ruff
        stages: [commit, manual]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
  - hooks:
      - id: isort
        stages: [commit, manual]
        name: isort (python)
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
  - hooks:
      - id: black
        stages: [commit, manual]
    repo: https://github.com/psf/black
    rev: 23.7.0
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.3
    hooks:
      - id: commitizen
        pass_filenames: false
        stages: [push]
