fail_fast: true
default_stages: [pre-commit]
repos:
  - hooks:
      - id: end-of-file-fixer
        stages: [pre-commit, manual]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - args:
          - --fix
          - --exit-non-zero-on-fix
        id: ruff
        stages: [pre-commit, manual]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.275
  - hooks:
      - id: isort
        stages: [pre-commit, manual]
        name: isort
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
  - hooks:
      - id: black
        stages: [pre-commit, manual]
    repo: https://github.com/psf/black
    rev: 22.10.0
  - repo: local
    hooks:
      - id: mypy-apiserver
        name: mypy-apiserver
        entry: cd apiserver && mypy .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: mypy-cli
        name: mypy-cli
        entry: cd cli && mypy .
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: pytest
        stages: [pre-commit]
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
