services:
  anki:
    image: thisisnttheway/headless-anki:latest
    container_name: anki-headless
    ports:
      - "8765:8765" # AnkiConnect
      - "5900:5900" # VNC (only needed for initial sync login)
    environment:
      - ANKICONNECT_WILDCARD_ORIGIN=1
      - VNC_PASSWORD=${VNC_PASSWORD} # Value loaded from local .env
    volumes:
      - ./anki_data:/data
    restart: always
