[tool.ruff]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade
]

# Same as Black.
line-length = 79

target-version = "py311"

[tool.black]
line-length = 79
experimental-string-processing = true

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version = "0.1.0"
update_changelog_on_bump = true
major_version_zero = true

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
