[tool.ruff]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade
]
line-length = 79 # Same as Black.
target-version = "py39"
exclude = [
    "uncommitted",
]

[tool.black]
line-length = 79
preview = true
organize-imports = false

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 79
profile = "black"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version = "0.1.0"
update_changelog_on_bump = true
major_version_zero = true

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
exclude = [
    "uncommitted",
]
