[project]
name = "cli"
version = "0.1.0"
description = ""
authors = [
    {name = "Eric Janto",email = "jantoeric@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13" # Restricted by spacy
dependencies = [
    "spacy (>=3.8.5,<4.0.0)",
    "en-core-web-trf @ https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0.tar.gz",
    "pydantic (>=2.12.5,<3.0.0)",
    "typer (>=0.15.3,<0.22.0)",
    "rich (>=14.3.0,<15.0.0)",
    "ebooklib (>=0.19,<0.21)",
    "beautifulsoup4 (>=4.14.3,<5.0.0)",
    "click (==8.1.8)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "src" }
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
black = "^25.1.0"

[tool.poetry.scripts]
lex-cli = "src.cli:main"
